### ISSUE TITLE
Force to import from barrel

### ISSUE THREAD

**Issue by michaeljota** [buehler/typescript-hero#107]
There is somehow to import _always_ from barrel files? Sometimes it does import from barrel, but sometimes it does not.

**Comment by buehler** [comment]
What does a `barrel` file mean?
I've no idea what you mean 😅

**Comment by michaeljota** [comment]
From [Angular 2 Glosary](https://angular.io/docs/ts/latest/guide/glossary.html#!#B)

> A barrel is a way to rollup exports from several ES2015 modules into a single convenient ES2015 module. The barrel itself is an ES2015 module file that re-exports selected exports of other ES2015 modules.

**Comment by buehler** [comment]
Well actually the code should process all those exporting files. Exports are parsed and processed after the files are parsed with the compiler.

Well there can be some issues with *.d.ts files since there are like a million ways to write those declarations. Can you make an explicit example?

The files that I'm using are working more or less.

**Comment by flubbes** [comment]
It seems like this issue is related to the one I'm having. I hope this will provide more information on how to fix this. 

I have set up a repository for reproducing the possible misbehavior under [flubbes/TypescriptHeroBarrelMisbehavior](https://github.com/flubbes/TypescriptHeroBarrelMisbehavior)

Thanks in advance
