### ISSUE TITLE
The lightbulb it's not show

### ISSUE THREAD

**Issue by michaeljota** [buehler/typescript-hero#123]
#### System information

- OS: Windows 10 AU
- TypeScript Hero version: 0.10.0
- VSCode version: 1.7.1

#### Description

The lightbulb it's not show.

##### Steps to reproduce

1. Make an error that Hero it's able to resolve, like missing import.
2. The error it's showed but the Hero lightbulb it's not.

**Comment by buehler** [comment]
Well, it depends if the missing symbol is found in the symbol-index. Imagine a code like this:
```typescript
let a = laksjdfalksdjflaksdjf();
```

Now I'm pretty sure, that this symbol is not in my index, so I don't wanna see the light bulb, since it's impossible to resolve the error.

Would it be more "intuitive", if the bulb is shown with the message "cannot resolve symbol laksjdfalksdjflaksdjf" ?

**Comment by michaeljota** [comment]
The problem is it is not showed in any case. Not one it's unable to solve, but ones that should be able to do.

**Comment by buehler** [comment]
I do not know if I really "fixed" the problem, but the light bulb should show and inform you if it cannot fix / import a symbol:

![light bulb](https://dl.dropboxusercontent.com/spa/agn3r6rkwi4rxn7/4-2mbvhb.png)
