### ISSUE TITLE
TypeScript Toolbox 

### ISSUE THREAD

**Issue by michaeljota** [buehler/typescript-hero#129]
#### System information

- OS: Windows 10 AU
- TypeScript Hero version: 0.10.1
- VSCode version: 1.7.2

#### Feature 

There are several features in [TypeScript Toolbox](https://github.com/cybertim/vscode-gengetset) that are useful, but also other that collides with this. Maybe you could join an develop just one extension? Idk. If you could not, well, as I said, several features in TSTB are useful, you should try to port them in here.  

#### Reason

The reason to join would be for us to have one extension that would really help us as developers. And for port some of the features, would be to have them here. 

Cheers!

**Comment by buehler** [comment]
Hey @michaeljota 
Funny you mention the TypeScript Toolbox :-) It was the reason why I started TypeScript Hero 😉 
I definitely will port those features. Which features do you mean in particular?
What I've got planned:
- Generate constructor for a class
- Generate methods / properties

What I'm actually developing is "Implement interface / abstract class" into an existing class.

Cheers

**Comment by michaeljota** [comment]
A getter/setter generator for private properties would be awesome, beside the ones you already mention.

**Comment by cybertim** [comment]
Since the toolbox started out as a 'generator' for getter and setters, because it would take me less time building an extension than typing all these get/set functions for a project i was doing, in the end sorting imports is more its core business now :-) (with the limited stuff vscode was capable of at the time).

@michaeljota tipped me about Hero and i must say, it is the first extension handling imports correctly (in a long line of 'auto import' extensions now available). 

Only thing i I noticed it doesn't really index custom-made node_modules with build in .d.ts files, I will probably look into this, because it is more work for me to start adding lightbulbs and such new stuff now available in vscode instead of letting this index custom modules ;-)

(im the creator of the toolbox btw)

**Comment by buehler** [comment]
Hey @cybertim 
Cool, hi there 😄 

I've to admit, I saw your extension a while ago and it actually inspired me to create typescript hero. So, your extension is kinda like the father of this one ;-)

I'd be really glad if we could join forces! What I'm working on right now is to generate properties and methods in classes, so I can introduce the feature to automatically implement methods from interfaces and abstract classes.

Furthermore I'd like to generally introduce code generation like your extension does.

If I remember it correctly, back in the day, the biggest difference between nearly all auto import extension and mine is, that I use the typescript - compiler to generate an AST out of a source file instead of parsing them with regex.
This has actually 2 big pros:
- Performance is waaaaay up to the roof
- It does not fail when some syntax thingies change in the language since it's parsed by the compiler

I think it would be possible to join our efforts and I'd really could use a helping hand ;-)

Cheers
Chris

**Comment by buehler** [comment]
@cybertim All the magic happens in the `TsResourceParser` as well as in the `ResolveIndex`
There you find a method for `findFiles` that does resolve all files in the workspace (or apparently not) :-)

**Comment by cybertim** [comment]
Yesterday I already went through a bunch of code, looks nice, guess you did some C# prior? Lots of stuff (especially async/await) was quite new to me (as Java was my root for years) looks cleaner than the Promise.then() hell I created ;-) Something to remember for the next Typescript project.

But I found the issue, the findFiles filters the `dist` directory, but a lot of node_modules in typescript libraries use this internally as the folder to store the index.d.ts for instance.

One example is for instance: https://github.com/driftyco/ionic-native
Removing `dist` from the ignore list solves this partially.
The next issue with these nasty libraries is the fact they should be imported as `import {bla} from `ionic-native` and not `ionic-native/dist/es6` for instance.

I solved this with a dirty hack (if `dist` is in the path, cut it off from the import path).
Not sure if things like this should be introduced in your code right now.
Maybe typescript already released some specs about how to handle typescript dict file within your node_modules? Also didn't understand your code enough to add this 'hack' clean in your code as a PR yet, maybe later when I got some time left again ;)

Also, `.tmp` should really be added to the ignore list :) this will solve a lot of double indexed libraries for most people. 
And you can use `path.sep` to get the correct path seperator for the used OS, solved a bunch of issues for me with people using windows, not sure if this is an issue now in the code, but I saw some regexes for path replacement.

**Comment by buehler** [comment]
Hehe thanks :-) yea, I was a .Net coder for a long time ;-) I really like async await, and it's gonna be in ES7! (yay)

Oh, so that was / is the issue? Well maybe we should just exclude the dist (and all other special folders) only if they are not in `node_modules` / `typings` then? Because when you have a dist folder in your project to precompile stuff, it's gonna be indexed and duplicated :-(

We really need to have a look at those indexing strategies.

I'm currently generating properties and methods (with testing), but it shouldn't take much longer to enable this feature.

Good point for the `.tmp` did not think of that 😉 

And for the last point:  I did use `path.sep` but ran into some problems with windows (duh!) so I changed it into the regex. Afterwards it worked as expected. Still don't know what the real issue was :-/

**Comment by buehler** [comment]
Hey @cybertim 
May I close this discussion?

I'm happily waiting for your PR ;-)

**Comment by cybertim** [comment]
Ah yes this can be closed.
I think i'm going to experiment with the AST generation first in ts toolbox so eventually solving these resolving/path/typing location issues will be more universal and easy to use in a PR and maybe even more modular so it can be used with hero like a module or something so we are not getting to many fragmented projects doing/trying the same thing, but I have to dive in this AST stuff first (when i have time :)).

**Comment by buehler** [comment]
Hehe alright ;-)
As I mentioned, we can join forces ;-)
We could merge the extensions into one IDE extension to help developers around the world. I've got plans for property and constructor generation as well.

Thanks for the effort!
