### ISSUE TITLE
Spaces still inserted around imports even when disabled in settings

### ISSUE THREAD

**Issue by axefrog** [buehler/typescript-hero#179]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may event implement it and send a PR which would be very appreciated>

#### System information

- OS: Windows 10
- TypeScript Hero version: 0.12.0
- VSCode version: 1.10.2

#### Description

I don't want spaces around my imports, and I've disabled that setting, but it's still happening. I've tried restarting VS Code, and re-checking that the setting is still there, but the issue persists.

##### Steps to reproduce

![image](https://cloud.githubusercontent.com/assets/298883/24680044/b8eec2e8-19d2-11e7-9b97-0b7820bf9f3c.png)

![vscode-typescript-hero-import-spaces-bug](https://cloud.githubusercontent.com/assets/298883/24680134/1182235a-19d3-11e7-9d1f-6f9ed59eede0.gif)

**Comment by buehler** [comment]
Hey @axefrog 
Actually this is the feature that is given to you by typescript and vscode itself. VSCode introduces those "autoimport" features as well. They only have some down-sides until some further updates:
- They use " instead of ' (not configurable, last time I checked)
- They only can auto import something that has been imported at least once.

Sadly, TSH did not recognize your package :-(

But thanks for the gif, it clarified the issue in an instant!

Cheers
Chris
