### ISSUE TITLE
Allow user to search within outline

### ISSUE THREAD

**Issue by thekalinga** [buehler/typescript-hero#225]
#### System information

- OS: Ubuntu 14.04
- TypeScript Hero version: 1.1.0
- VSCode version:  1.14.0-insider

#### Feature: Outline search

Though we have outline, there is no way to search for the item of interest.

#### Reason

Would be really handy if the outline accompanies search aswell so that we dont need to scroll to eyeball the item

**Comment by buehler** [comment]
Hey @thekalinga 

The least I could provide would be a picker box in vscode itself since the view that the extension adds does not provide any search features or interfaces.

But for that case, there is already something: cmd+P and enter `@` into the "I can do everything bar" of vscode. There are all symbols of your file.

Do you think it would be handy to have a seperated search box?

Cheers

**Comment by thekalinga** [comment]
@buehler The current symbols search screen is good enough for searching (- outline).

I close explorer most of the time as its a waste of real estate if you use shortcuts most of the time.

Its would be be nice if this outline can be moved to dialog & search be present there (like eclipse does).

In the current state, Looks to me(now) its better **not to implement** this as the ultimate thing to do is to merge outline & symbols view (+ have the current ability to be stick in the explorer aswell if someone whats it open always).

Thanks for your response.

Sorry for wasting your time

**Comment by buehler** [comment]
@thekalinga no worries :-)

This was not wasted time, actually it was a good idea to think about it again. As it seems that this "feature" is actually pretty useless.

So I'm actually thinking about getting rid of the view (and if there is the need for it make an own extension from it)

Thanks and Cheers!
