### ISSUE TITLE
Code Outline is empty

### ISSUE THREAD

**Issue by Catscratch** [buehler/typescript-hero#234]
Hi.

#### System information

- OS: Windows 10 x64
- TypeScript Hero version: 1.1.0
- VSCode version: 1.13.1

#### Description

My code outline window is simply empty. :-)

##### Steps to reproduce

1. Install Visual Studio Code
2. Install extension
3. Restart
4. Choose a typescrypt file (.ts)
5. Extend outline tab and see its empty

Sadly, I can't tell anymore. I can only tell what I see. :-)

**Comment by buehler** [comment]
Humm :-)
Well in an unreleased version, I removed the outline, since you actually can use `cmd+shift+o` to open a cool outline from vscode itself with search and everything. So this is not really needed. Maybe I'm gonna create another extension just for that purpose, but then with multiple languages, not only TS

**Comment by buehler** [comment]
Well actually, there are people who need that feature. So I'm gonna reenable it :)

**Comment by buehler** [comment]
@Catscratch still empty?
