### ISSUE TITLE
Since 2.0, typescriptHero.imports.grouping can't be overriden

### ISSUE THREAD

**Issue by Zephir77167** [buehler/typescript-hero#377]
#### System information

- OS: MacOs High Sierra
- TypeScript Hero version: 2.0.0
- VSCode version: 1.19.2

#### Description

Since 2.0.0, typescriptHero.imports.grouping can't be overriden in VSCode configuration.

##### Steps to reproduce

1.
```js
"typescriptHero.imports.grouping": [
	"Modules",
    "Plains"
]
```

2. Save. Doesn't change from the default behavior.

I tried restarting VSCode, no dice

Thanks in advance!

**Comment by Da13Harris** [comment]
I've got the same issue on Windows 10 (Creators Update), with the same versions of TS Hero & VS Code.

Here are my related config settings:
```
    "typescriptHero.imports.multiLineWrapThreshold": 400,
    "typescriptHero.imports.multiLineTrailingComma": false,
    "typescriptHero.imports.grouping": [
        "/@angular/",
        "/rxjs/",
        "/primeng/",
        "/.module/",
        "/.view-model|.model/",
        "/.component/",
        "/.service/",
        "/.directive/",
        "/.pipe/"
    ],
```
The same import groups worked as expected on the pre-2.0 version of TS Hero.

**Comment by kevindqc** [comment]
Also the help still talking about using `typescriptHero.imports.importGroups` but it seems that VSCode expects `typescriptHero.imports.grouping`.

**Comment by kevindqc** [comment]
It seems using `typescriptHero.imports.importGroups` instead of `typescriptHero.imports.grouping` and ignore the VSCode error "Unknown configuration setting" works fine.

So if the setting to use is supposed to be `typescriptHero.imports.importGroups`
- Need to update what VSCode uses for validation (is it the configuration section in package.json?)

If the setting to use is supposed to be `typescriptHero.imports.grouping`
- Probably need to change the code to make it work.

**Comment by buehler** [comment]
@kevindqc Whoops 😱 

This will be fixed as soon as possible. Thanks for the investigation!
