### ISSUE TITLE
Is there a tutorial on how to develop / debug typescript-hero?

### ISSUE THREAD

**Issue by shobhitg** [buehler/typescript-hero#384]
Hi @buehler 

This is not a bug, but just a request.
At times I wish to contribute to this extension. But don't know where to start.

Can you please document some instructions on how one shall develop and debug Typescript?

Let us say you start from scratch, steps would be:
1. Cloning a new repo
2. `yarn install`
3. `yarn run build`
4. `yarn run develop` in one terminal
5. `yarn run test:watch` in another terminal

What next? How do I debug, as in setting breakpoints and hitting them?

It would be awesome if you list all the steps or could make a small screencast video where you show how you debug.

This extension has made life really easy, but I feel its mostly one or two man job till now. We need more people contributing. And for that we need instructions that help others begin.

-Shobhit

**Comment by buehler** [comment]
Hey @shobhitg 

Of course, I'm happy to help. Up until know I did most of the work by myself. Some other kind contributors helped me along the way. But I'm really happy that more people get involved with the extension. Especially since the last version needed to break a feature because of some serious memory issues.

Actually, you need to get the code of course, after that I used to work as follows:

1. `yarn install`
2. `yarn develop` // <-- this starts the typescript compiler
3. code stuff :-)
4. Launch the extension via the vscode debugger as described in the `.vscode/launch.json` file.

With those steps, you can use vscode to debug the application with breakpoints and all other funny things.

Hope I could help, feel free to ask any other questions. Or close the ticket by yourself if you are satisfied with the answer ;-)

**Comment by shobhitg** [comment]
okay, I am trying to use the launch.json, and if I try to set a breakpoint I get this inactive breakpoint with message: `Breakpoint ignored because generated code not found(source map problem?)`.

I can't find sourcemap files in `out` folder or anywhere else. Do you see sourcemap files in your env? If yes, which folder. Do you think I am missing any step which generates the sourcemap files?

**Comment by shobhitg** [comment]
Oh figured out.

It seems that `--sourceMap` option wasn't enabled by default for `develop` script.
I think sourceMaps should be default for `develop` mode.

**Comment by buehler** [comment]
Actually, they are enabled by default: https://github.com/buehler/typescript-hero/blob/develop/tsconfig.json#L4

**Comment by shobhitg** [comment]
Yes, somehow now sourcemap files are showing up but day before yesterday they were not. I think it has something to do with some improvements you made recently.
Anyway, now I can debug fine. Next step is to understand the code. I will close this issue.

**Comment by buehler** [comment]
@shobhitg 
I'll add documentation (jsdoc) back as soon as possible. as well as testing. I desperately tried to use JEST for testing. But the damn vscode context does hack the node require function. So it's not possible to use jest for vscode testing. (since jest is not runnable from code)
