### ISSUE TITLE
New import location at the top of the file is not what expected.

### ISSUE THREAD

**Issue by DiamondeX** [buehler/typescript-hero#73]
Good extension! But...

1. I expect that new imports are added at the top of the file but after `"use strict"` directive and
2. possibly preserving alphabetic order.
3. It is also helpful to leave header comments adove import location.
4. Yet the comment like `//imports` may help to determine preferrable position for them.
5. Ability to use three common groups of imports delineated by blank lines: provided by node (fs, path, http etc.), provided by npm (express, angular, chalk etc.) and project specific (defined with path)
6. Abilities, reflected to this [linting rule](http://palantir.github.io/tslint/rules/ordered-imports/)

At least some of this features would be greatly appreciated!

**Comment by buehler** [comment]
Hey @DiamondeX 
Thanks for your thoughts :-)

1. good point! but why do you even use `"use strict"` as I'm aware of, typescript does not need use strict anymore
2. It actually does sort the imports when you use "organize imports" and since workspace files are preceeded by a dot, they are sorted at the top.

6 counts to the sorting thingy :-)

For the fifth point, it would be nice, but it's kinda hard to achieve this

**Comment by DiamondeX** [comment]
About "use strict" consider this [answer](http://stackoverflow.com/a/31395185/3381938) at stackoverflow

**Comment by buehler** [comment]
Yea you are right, but I just checked, "use strict" is emitted by the typescript compiler. Or am I wrong?

Well anyway, since "use strict" has to be on the top of a file, I'll prevent the organizer to add imports before the use strict ;-)

On the other thoughts I'll have a look at when I got time for enhancements

**Comment by DiamondeX** [comment]
@buehler, Should I open new issues for some of the above features except one with use strict?

**Comment by buehler** [comment]
@DiamondeX yea, if you don't mind, it would be nice!
Some of them should be covered with the other issue #80 
A possible plan would be to introduce special comments (like `// TSH:`) or so, that allow grouping of imports
